name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

      mariadb:
        image: mariadb:11.8
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "1"
          MARIADB_CHARACTER_SET_SERVER: utf8mb4
          MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
        ports:
          - 3306:3306
        options: --health-cmd="mariadb-admin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        moodle-branch:
          - 'MOODLE_502_STABLE'
          - 'MOODLE_501_STABLE'
          - 'MOODLE_500_STABLE'
          - 'MOODLE_405_STABLE'
        php:
          - '8.4'
          - '8.3'
          - '8.2'
          - '8.1'
        database: ['mariadb', 'pgsql']
        exclude:
          # Moodle 5.2 doesn't support PHP 8.1 or PHP 8.2, so exclude this combination.
          - moodle-branch: 'MOODLE_502_STABLE'
            php: '8.2'
          - moodle-branch: 'MOODLE_502_STABLE'
            php: '8.1'
          # Moodle 5.1 doesn't support PHP 8.1 or PHP 8.2, so exclude this combination.
          - moodle-branch: 'MOODLE_501_STABLE'
            php: '8.2'
          - moodle-branch: 'MOODLE_501_STABLE'
            php: '8.1'
          # Moodle 5.0 doesn't support PHP 8.1, so exclude this combination.
          - moodle-branch: 'MOODLE_500_STABLE'
            php: '8.1'
          # Moodle 4.5 doesn't support PHP 8.4, so exclude this combination.
          - moodle-branch: 'MOODLE_405_STABLE'
            php: '8.4'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: plugin
          submodules: recursive

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          coverage: none

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install moodle-plugin-ci
        run: moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
          CODECHECKER_IGNORE_PATHS: 'editor,library,reporting'
      - name: PHP Lint
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phplint

      - name: Moodle Code Checker
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpcs --max-warnings 0

      - name: Moodle PHPDoc Checker
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpdoc --max-warnings 0

      - name: Validating
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci savepoints

      - name: PHPUnit tests
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpunit --fail-on-warning

      - name: Behat features
        if: ${{ always() }}
        run: moodle-plugin-ci behat --profile chrome

      - name: Mark cancelled jobs as failed
        if: ${{ cancelled() }}
        run: exit 1

